name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      DOCKER_PLATFORMS: linux/amd64,linux/armhf,linux/arm64

    steps:
    -
        name: Checkout
        uses: actions/checkout@v3
    -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0
    -
        name: setup docker buildx
        uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true
    -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    - 
      name: Build the Docker image
      run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes && docker buildx build --platform linux/amd64,linux/armhf,linux/arm64 -t simeononsecurity/docker-pharos-control:latest --progress=plain --push .
    -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: simeononsecurity/docker-pharos-control:latest
          
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.PAT_TOKEN }}

    - name: Build the simeononsecurity/docker-pharos-control:latest Docker image for Github Registry
      run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes && docker buildx build --platform linux/amd64,linux/armhf,linux/arm64 -t ghcr.io/simeononsecurity/docker-pharos-control:latest --progress=plain --push .

